aria2:
  image: mauchede/aria2:1.18.8
  command: --enable-rpc --quiet --log=- --log-level=warn --rpc-listen-all=true --rpc-secret=ThisTokenIsNotSoSecretChangeIt
  ports:
    - 6800:6800

webui-aria2:
  image: mauchede/webui-aria2
  environment:
    - "RPC_HOST=127.0.0.1"
    - "RPC_SECRET=ThisTokenIsNotSoSecretChangeIt"
  ports:
    - 80:80
